### ISSUE TITLE
Token verification fails during authentication for non base64 encoded secret 

### ISSUE THREAD

**Issue by santiagorp** [auth0-samples/auth0-spring-mvc-sample#13]
The version `1.1.2` of **auth0-spring-mvc** does not check if the client secret is encoded in base64 and it fails for non encoded secrets.

The `pom.xml` from the samples should be updated to use the version `1.2.0`.

**Comment by jimmyjames** [comment]
Hi @santiagorp, as this issue is nearly two years old and this sample and supporting SDKs have been updated since then, I'm going to close this issue. If you are still encountering difficulties, don't hesitate to reopen this issue or open a new one (including updated information about the problem). Thanks!
